name: lemon
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  font_awesome_flutter: ^9.2.0
  jiffy: ^5.0.0
  faker: ^2.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  animated_splash_screen: ^1.2.0
  logger: ^1.1.0

  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  stream_chat_flutter_core: ^3.5.0
  
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  cloud_functions: ^3.2.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:

  
  uses-material-design: true

  assets:
   - images/backgroundForSelectUserPage.jpg
  #   - images/a_dot_ham.jpeg


  
  #fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700